### ISSUE TITLE
Playground- flexible panels

### ISSUE THREAD

**Issue by jamesnw** [oddbird/sass-site#82]
Drag to expand/collapse input/output/console panel widths: see [design proposal](https://xd.adobe.com/view/84c872fe-0e51-46e4-a59c-f72aab2b8c6a-d19b/screen/413c2a93-be31-4b54-8bbe-ef30b8af2dd0/)

**Comment by jamesnw** [comment]
@stacyk or @mirisuzanne This strongly impacts the grid layout, I'd like to talk through it with someone to get it to a place where styling can happen easily.

**Comment by mirisuzanne** [comment]
At a quick glance, the grid is defined on `.sl-c-playground` - currently an even `1fr 1fr` split. If you provide a custom property on that element using inline styles (something like `--input-track-width: <user-set-width-for-input>`), we can set the grid to use that value when defined.

Based on sprint planning, I think it's best to pull in Stacy on this if you need more.

**Comment by jamesnw** [comment]
Moved upstream to https://github.com/sass/sass-site/pull/1204
